//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.29 at 09:06:46 PM SAMT 
//


package generate;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="client" type="{http://spring.io/guides/gs-producing-web-service}client"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "client"
})
@XmlRootElement(name = "getClientResponse")
public class GetClientResponse {

    @XmlElement(required = true)
    protected Client client;

    /**
     * Gets the value of the client property.
     *
     * @return possible object is
     * {@link Client }
     */
    public Client getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     *
     * @param value allowed object is
     *              {@link Client }
     */
    public void setClient(Client value) {
        this.client = value;
    }

}
